### ISSUE TITLE
Install Yarn on your local machine & add node_modules to gitignore

### ISSUE THREAD

**Issue by MikeRogers0** [mattmarc44/sass-site#2]
https://yarnpkg.com/lang/en/docs/install/#windows-stable - Install instructions here

I added `node_modules` to version control (Oh no!), let get you setup with yarn so we can remove that folder :D

**Comment by mattmarc44** [comment]
Didn't we do this already?

**Comment by MikeRogers0** [comment]
I think so! I'm clearing out my old open PRs/Issues heh!
